### ISSUE TITLE
scanner fails if /tmp is on a different filesystem than the filesystem being scanned on linux

### ISSUE THREAD

**Issue by cmedianu** [google/log4jscanner#18]
log4jscanner.go:119: Error: scanning oracle/product/19.0.0.0/dbhome_1/suptools/tfa/release/tfa_home/jlib/tfa.war: overwriting product/19.0.0.0/dbhome_1/suptools/tfa/release/tfa_home/jlib/tfa.war: rename /tmp/1487074654 oracle/product/19.0.0.0/dbhome_1/suptools/tfa/release/tfa_home/jlib/tfa.war: invalid cross-device link

**Comment by ericchiang** [comment]
Thanks! I'll try to fix this when sending a PR for #13

**Comment by cmedianu** [comment]
@ericchiang  thanks for fixing it! When will it be released as linux binary?
