### ISSUE TITLE
Replace io.ReadAll usage with pre-allocated buffers of appropriate size

### ISSUE THREAD

**Issue by lyoung-confluent** [google/log4jscanner#27]
There is a potential performance/memory improvement when reading the contents of a _nested_ jar by replacing `io.ReadAll`:

Internally, `io.ReadAll` will allocate a byte slice ([initially 512 bytes](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/io/io.go;l=627)) and then expand the size of the buffer [as needed](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/io/io.go;l=631) when each `(io.Reader).Read` call is executed. In practice this means a slice will be allocated and resized multiple times when reading most jar files.

Because the size of the file is [already known](https://github.com/google/log4jscanner/blob/c92bc8488ea44ca914f615b52aebe6b00bc11710/jar/jar.go#L275) the buffer could be allocated initially at the exact size required. This is essentially what [os/io.ReadFile](https://pkg.go.dev/os#ReadFile) does internally and [the implementation](https://cs.opensource.google/go/go/+/refs/tags/go1.17.5:src/os/file.go;l=693) could be copied almost exactly into a helper method.

**Comment by ericchiang** [comment]
Hey @lyoung-confluent,

We generally won't take performance CLs unless there's an associated benchmark that demonstrates that benefit it meaningful. Premature optimization and all that :)

We had someone looking at the performance internally, and there are definitely places to improve.

If you are looking into improve performance, please look at a tool like https://pkg.go.dev/golang.org/x/perf/cmd/benchstat so there are comparisons.

**Comment by mknyszek** [comment]
@lyoung-confluent See #40 which should resolve this.

**Comment by ericchiang** [comment]
Closed via https://github.com/google/log4jscanner/pull/40
