### ISSUE TITLE
sudo: log4jscanner: command not found

### ISSUE THREAD

**Issue by cdo9** [google/log4jscanner#30]
With **go version go1.17.5 darwin/amd64** on Mac OS.
I did this command : `go install github.com/google/log4jscanner@latest`
But when i type `sudo log4jscanner /System/Volumes/Data` it keeps saying `sudo: log4jscanner: command not found`
First time using go, maybe there is an extra step that i am missing ?

**Comment by loeffel-io** [comment]
You could simply download the bin from the release page; no go required

**Comment by ericchiang** [comment]
sudo overrides the `PATH` environment variable before running your command, you can see that by running

```
sudo env
```

Since you've installed log4jscanner in a local user path, it's likely not in a root `PATH` directory. Either move it to one of those directories or running from a relative path

```
sudo ./log4jscanner
```
