### ISSUE TITLE
Error scanning - negative offset

### ISSUE THREAD

**Issue by pannemra** [google/log4jscanner#42]
Getting the error below when scanned on Cloudera cluster edge node on RedHat 7 Linux VM.

One of the zip file it scanned has name like  .¶i84ianid.xetntwmu¶.com-a-00000583-c-00134550_<clusterName>_0_2021-01-17_02-00-02.tgz. Not sure special character in the file name caused the error.

2022/01/06 19:45:31 log4jscanner.go:120: Error: scanning /var/lib/smartsense/hst-agent/data/tmp/<serverName>/<server>.¶i84ianid.x
etntwmu¶.com-a-00000583-c-00134550_<clusterName>_0_2021-01-17_02-00-02/services/HBASE/components/Client/DEFAULT/conf/hbase-site.jar: opennig file
 as a ZIP archive: readat //var/lib/smartsense/hst-agent/data/tmp/<serverName>/<server>.¶i84ianid.xetntwmu¶.com-a-00000583-c-0013
4550_<ClusterName>_0_2021-01-17_02-00-02/services/HBASE/components/Client/DEFAULT/conf/hbase-site.jar: negative offset

**Comment by davidsonff** [comment]
P.S. - The .tgz file unzips properly on the OS.

**Comment by ericchiang** [comment]
Unfortunately it's going to be really hard for us to debug this without a replication case. Is this OSS you can provide?

**Comment by davidsonff** [comment]
The problem was that our .zip file was corrupted, apparently. This can be closed.
